import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, Bot, Check, ChevronDown, CircleHelp, Globe2, Layers3, Menu, MessageCircle, MonitorSmartphone, Network, Play, ScanLine, Sparkles, X, Zap } from 'lucide-react';
import './style.css';

const services = [
  { n: '01', icon: Globe2, title: 'Websites that work harder', text: 'Distinctive websites and digital products, shaped around how your customers actually move.' },
  { n: '02', icon: Layers3, title: 'ERP, your way', text: 'Bring finance, stock, sales and operations together. Run it in your cloud or on your own servers.' },
  { n: '03', icon: Network, title: 'People, in sync', text: 'A calmer way to manage people, payroll, leave and the everyday rhythm of your team.' },
  { n: '04', icon: Bot, title: 'AI with a day job', text: 'Useful agents and chatbots that answer, automate and surface the next best action.' },
];

function Dashboard() {
  return <div className="dash-wrap" aria-label="Illustration of an ERP analytics dashboard">
    <div className="orbit orbit-one"/><div className="orbit orbit-two"/>
    <div className="dash-card">
      <div className="dash-top"><div className="dash-brand"><span className="mini-mark">✳</span> LimeOS <span className="dash-label">OVERVIEW</span></div><span className="avatar">LT</span></div>
      <div className="dash-title">Good morning, team <span>✦</span></div><div className="dash-sub">Here’s what’s happening across your business.</div>
      <div className="metric-row"><div className="metric"><small>REVENUE · THIS MONTH</small><strong>$84,260</strong><em>↗ 12.8%</em></div><div className="metric"><small>ORDERS FULFILLED</small><strong>1,284</strong><em>↗ 8.2%</em></div></div>
      <div className="chart-head"><b>Revenue overview</b><span>Last 7 months⌄</span></div>
      <div className="chart"><div className="chart-grid"><i/><i/><i/><i/></div><svg viewBox="0 0 480 110" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#b5e44a" stopOpacity=".28"/><stop offset="1" stopColor="#b5e44a" stopOpacity="0"/></linearGradient></defs><path d="M0 87 C25 82 36 74 58 79 S93 60 119 68 S156 53 177 60 S212 38 239 48 S273 35 296 42 S337 22 358 33 S399 18 420 25 S455 10 480 13 V110 H0Z" fill="url(#fill)"/><path d="M0 87 C25 82 36 74 58 79 S93 60 119 68 S156 53 177 60 S212 38 239 48 S273 35 296 42 S337 22 358 33 S399 18 420 25 S455 10 480 13" fill="none" stroke="#b5e44a" strokeWidth="3"/></svg><div className="months"><span>JAN</span><span>FEB</span><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span><span>JUL</span></div></div>
      <div className="dash-foot"><span><i className="live-dot"/> All systems in sync</span><span>Updated just now</span></div>
    </div>
    <div className="float-note note-ai"><span className="note-icon"><Sparkles size={15}/></span><div><small>AI INSIGHT</small><b>Stock is trending up</b></div><span className="note-up">↗</span></div>
    <div className="float-note note-mobile"><div className="phone-icon"><MonitorSmartphone size={17}/></div><div><small>YOUR BUSINESS</small><b>In your pocket.</b></div></div>
    <div className="spark spark-a">✳</div><div className="spark spark-b">✳</div>
  </div>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  const submit = (e) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    const subject = encodeURIComponent(`Let’s build something — ${data.get('name')}`);
    const body = encodeURIComponent(`Hi Lime Tech,\n\n${data.get('message')}\n\n${data.get('name')}\n${data.get('email')}`);
    window.location.href = `mailto:hello@limetech.io?subject=${subject}&body=${body}`;
    setSent(true);
  };
  return <>
    <header className="nav-shell"><a href="#top" className="brand"><img src="/lime-logo.png" alt="Lime Tech"/><span className="brand-tag">DIGITAL, GROWN WELL.</span></a><button className="mobile-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#what" onClick={closeMenu}>What we do</a><a href="#platform" onClick={closeMenu}>LimeOS</a><a href="#approach" onClick={closeMenu}>Our approach</a><a className="nav-cta" href="#contact" onClick={closeMenu}>Let’s talk <ArrowUpRight size={15}/></a></nav></header>
    <main id="top">
      <section className="hero section-pad"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> TECHNOLOGY FOR WHAT’S NEXT</div><h1>Make your<br/>next move <span className="lime-word">count<span className="period">.</span></span></h1><p className="hero-intro">We build the digital foundations that help ambitious businesses move forward—from their first website to the systems that run the whole show.</p><div className="hero-actions"><a href="#contact" className="button button-lime">Tell us what you’re building <ArrowUpRight size={17}/></a><a href="#what" className="text-link">Get to know us <ArrowDownRight size={16}/></a></div><div className="hero-note"><span className="note-rule"/> BIG IDEAS. THOUGHTFUL BUILDING. REAL-WORLD RESULTS.</div></div><Dashboard/><div className="hero-index"><span>01</span><i/> DIGITAL PARTNER FOR GROWING TEAMS</div></section>
      <section className="ticker"><div className="ticker-track">{['WEB EXPERIENCES','CONNECTED OPERATIONS','HUMAN-CENTRED HR','PRACTICAL AI','BETTER BUSINESS DATA','WEB EXPERIENCES','CONNECTED OPERATIONS'].map((x,i)=><span key={i}>{x}<b>✳</b></span>)}</div></section>
      <section className="services section-pad" id="what"><div className="section-heading"><div><div className="eyebrow dark-eyebrow"><span className="eyebrow-dot"/> WHAT WE MAKE POSSIBLE</div><h2>One partner.<br/><span className="muted-heading">Room to grow.</span></h2></div><p>Good technology should feel like momentum. We bring the right people, products and ideas together to make work flow better.</p></div><div className="service-grid">{services.map(({n,icon:Icon,title,text})=><article className="service-card" key={n}><div className="service-top"><span>{n} / 04</span><Icon size={22} strokeWidth={1.5}/></div><h3>{title}</h3><p>{text}</p><a href="#contact" aria-label={`Ask us about ${title}`}><ArrowUpRight size={19}/></a></article>)}</div><div className="service-foot"><span>FROM A GREAT FIRST IMPRESSION TO A BETTER RUNNING BUSINESS.</span><a href="#contact">Explore a project with us <ArrowRight size={15}/></a></div></section>
      <section className="platform section-pad" id="platform"><div className="platform-top"><div className="eyebrow"><span className="eyebrow-dot"/> MEET YOUR NEW BUSINESS HQ</div><div className="platform-stamp"><span>ONE CLEARER<br/>PICTURE</span><ScanLine size={28}/></div></div><div className="platform-layout"><div className="platform-copy"><div className="product-name"><span className="product-symbol">✳</span> Lime<span>OS</span></div><h2>Every moving part.<br/><span>Moving together.</span></h2><p>Meet the operating system for your business. LimeOS brings your people, processes and performance into one connected place—with the freedom to run in the cloud or on your own ground.</p><div className="platform-points"><div><span className="check-mark"><Check size={13}/></span> ERP + HRM, one connected core</div><div><span className="check-mark"><Check size={13}/></span> Built-in AI assistant and chat</div><div><span className="check-mark"><Check size={13}/></span> Forecasts that look ahead</div><div><span className="check-mark"><Check size={13}/></span> Mobile access, wherever work goes</div></div><a href="#contact" className="button button-outline">See what LimeOS can do <ArrowUpRight size={16}/></a></div><div className="platform-visual"><div className="platform-ring ring-1"/><div className="platform-ring ring-2"/><div className="platform-center"><span className="platform-spark">✳</span><strong>One business.<br/>A clearer picture.</strong><small>CONNECTED BY LIMEOS</small></div><div className="node node-erp"><Layers3/><span>ERP</span></div><div className="node node-hr"><Zap/><span>HRM</span></div><div className="node node-ai"><Bot/><span>AI + INSIGHTS</span></div><div className="node node-mobile"><MonitorSmartphone/><span>MOBILE</span></div><div className="connect-line line-1"/><div className="connect-line line-2"/><div className="connect-line line-3"/><div className="connect-line line-4"/></div></div></section>
      <section className="forecast section-pad"><div className="forecast-copy"><div className="eyebrow dark-eyebrow"><span className="eyebrow-dot"/> SEE A LITTLE FURTHER</div><h2>Less guesswork.<br/><span>More next steps.</span></h2><p>Spot the pattern while there’s still time to act. LimeOS turns everyday business data into forecasts and plain-language insights your team can actually use.</p><a href="#contact" className="text-link dark-link">Let’s talk about your data <ArrowRight size={16}/></a></div><div className="forecast-card"><div className="forecast-card-top"><div><small>DEMAND FORECAST</small><h3>A healthier view ahead.</h3></div><span className="forecast-chip">AI ASSISTED</span></div><div className="forecast-chart"><div className="forecast-y"><span>100</span><span>75</span><span>50</span><span>25</span></div><div className="forecast-plot"><div className="forecast-gridlines"><i/><i/><i/><i/></div><div className="actual-area"><svg viewBox="0 0 400 160" preserveAspectRatio="none"><path d="M0 125 C32 118 42 108 75 114 S111 92 137 98 S175 76 200 87 S238 68 267 74 S302 53 330 62 S367 42 400 43 V160 H0Z" fill="#dff0b7"/><path d="M0 125 C32 118 42 108 75 114 S111 92 137 98 S175 76 200 87 S238 68 267 74 S302 53 330 62 S367 42 400 43" fill="none" stroke="#6b9d22" strokeWidth="3"/></svg></div><svg className="future-line" viewBox="0 0 400 160" preserveAspectRatio="none"><path d="M0 125 C32 118 42 108 75 114 S111 92 137 98 S175 76 200 87 S238 68 267 74 S302 53 330 62 S367 42 400 43" fill="none" stroke="#6b9d22" strokeWidth="3" strokeDasharray="5 6"/></svg><div className="forecast-split"><span>ACTUAL</span><span>PROJECTED</span></div></div></div><div className="forecast-months"><span>JAN</span><span>FEB</span><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span><span>JUL</span></div><div className="forecast-tip"><Sparkles size={16}/><span><b>Looking good.</b> Demand is expected to rise 14% next quarter.</span><ArrowUpRight size={16}/></div></div></section>
      <section className="approach section-pad" id="approach"><div className="approach-aside"><div className="eyebrow"><span className="eyebrow-dot"/> HOW WE WORK</div><div className="approach-index">LT<br/><span>STUDIO / 01</span></div></div><div className="approach-main"><h2>Built with you.<br/><span>Ready for real life.</span></h2><div className="approach-bottom"><p>No mystery process. No technology for technology’s sake. Just a curious team, a clear plan and work made to earn its place in your business.</p><div className="steps"><div><b>01</b><span>Listen<br/><small>Start with the real problem.</small></span></div><div><b>02</b><span>Shape<br/><small>Map the right-sized solution.</small></span></div><div><b>03</b><span>Make<br/><small>Build, launch and keep improving.</small></span></div></div></div></div></section>
      <section className="contact section-pad" id="contact"><div className="contact-glow"/><div className="contact-top"><div className="eyebrow"><span className="eyebrow-dot"/> YOUR NEXT CHAPTER STARTS HERE</div><MessageCircle size={26} strokeWidth={1.3}/></div><div className="contact-grid"><div><h2>Got a good<br/>one in mind<span>?</span></h2><p>Tell us where you want to go. We’ll help you figure out how to get there.</p><div className="contact-email"><span>OR JUST DROP US A LINE</span><a href="mailto:hello@limetech.io">hello@limetech.io <ArrowUpRight size={15}/></a></div></div><form onSubmit={submit}><label>Your name<input required name="name" placeholder="What should we call you?"/></label><label>Email address<input required type="email" name="email" placeholder="you@company.com"/></label><label>What are you thinking?<textarea required name="message" rows="3" placeholder="A website, a better way to work, an ambitious idea…"/></label><button className="button button-lime" type="submit">{sent ? 'Email draft opened' : 'Start the conversation'}{sent ? <Check size={17}/> : <ArrowUpRight size={17}/>}</button><small className="form-note">Your email app will open with your note ready to send.</small></form></div></section>
    </main><footer className="footer"><a href="#top" className="footer-brand"><img src="/lime-logo.png" alt="Lime Tech"/></a><span>© {new Date().getFullYear()} LIME TECH. GROWN WITH PURPOSE.</span><div><a href="#what">SERVICES</a><a href="#platform">LIMEOS</a><a href="#contact">CONTACT</a></div><a className="back-top" href="#top" aria-label="Back to top"><ArrowUpRight size={17}/></a></footer>
  </>
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
